export default [
  {
    id: "1",
    title: "BIO DEGRADABLE",
    description:
      "PLASTIC THAT IS NOT RECYCLED AND GETTING MIXED WITH THE ORGANIC WASTE WHICH IS DISPOSED OF ON LAND ON THE WATER, CAUSES GREAT TO ANIMALS LIVE ONLINE AND OTHER FLORA AND FAUNA",
    image: require("./images/biodegradable.png"),
  },
  {
    id: "2",
    title: "RECYCLE",
    description:
      "PLASTIC THAT IS NOT RECYCLED AND GETTING MIXED WITH THE ORGANIC WASTE WHICH IS DISPOSED OF ON LAND ON THE WATER, CAUSES GREAT TO ANIMALS LIVE ONLINE AND OTHER FLORA AND FAUNA",
    image: require("./images/recycle.png"),
  },
  {
    id: "3",
    title: "ECO WASTE",
    description:
      "PLASTIC THAT IS NOT RECYCLED AND GETTING MIXED WITH THE ORGANIC WASTE WHICH IS DISPOSED OF ON LAND ON THE WATER, CAUSES GREAT TO ANIMALS LIVE ONLINE AND OTHER FLORA AND FAUNA",
    image: require("./images/ecowaste.png"),
  },
  {
    id: "4",
    title: "COMPOST",
    description:
      "PLASTIC THAT IS NOT RECYCLED AND GETTING MIXED WITH THE ORGANIC WASTE WHICH IS DISPOSED OF ON LAND ON THE WATER, CAUSES GREAT TO ANIMALS LIVE ONLINE AND OTHER FLORA AND FAUNA",
    image: require("./images/compost.png"),
  },
  {
    id: "5",
    title: "CONTAMINATION",
    description:
      "PLASTIC THAT IS NOT RECYCLED AND GETTING MIXED WITH THE ORGANIC WASTE WHICH IS DISPOSED OF ON LAND ON THE WATER, CAUSES GREAT TO ANIMALS LIVE ONLINE AND OTHER FLORA AND FAUNA",
    image: require("./images/contanimation.png"),
  },
];
